### ISSUE TITLE
A higher proposal 

### ISSUE THREAD

**Issue by jiewangjs** [asiloisad/pulsar-navigation-panel#3]
Hi, this has been an unique package that is helpful already in many scenarios. 
Recently, I have this thought that it would be even better that the tree item highlight would sync with editor page scrolling (without mouse clicking).
I know now if you click mouse anywhere in the editor, the tree highlight would jump to according position, and the proposal upward seems a step forward. 
Best regards

**Comment by asiloisad** [comment]
I have made a research, but i cannot find any api to catch the view scroll. If anyone has idea how to do it, the help will be appreciated.

**Comment by asiloisad** [comment]
A feature has been added https://github.com/bacadra/pulsar-navigation-panel/pull/5.
